parameters:
    cargador.class:  Gopro\Vipac\DbprocesoBundle\Service\Cargador
    proceso.class:  Gopro\Vipac\DbprocesoBundle\Service\Proceso

services:
    gopro_dbproceso_cargador:
        class: %cargador.class%
        calls:
            - [ setContainer,[ "@service_container" ] ]
        shared: false
    gopro_dbproceso_proceso:
        class: %proceso.class%
        calls:
            - [ setContainer,[ "@service_container" ] ]
        shared: false

