parameters:
    archivoexcel.class:  Gopro\MainBundle\Service\Archivoexcel
    archivozip.class:  Gopro\MainBundle\Service\Archivozip
    variableproceso.class:  Gopro\MainBundle\Service\Variableproceso

services:
    gopro_main_archivozip:
        class: %archivozip.class%
        calls:
            - [ setContainer,[ "@service_container" ] ]
        shared: false
    gopro_main_archivoexcel:
        class: %archivoexcel.class%
        calls:
            - [ setContainer,[ "@service_container" ] ]
        shared: false
    gopro_main_variableproceso:
        class: %variableproceso.class%
        calls:
            - [ setContainer,[ "@service_container" ] ]